packages:
  - apps/**
  - packages/**

catalogs:
  base:
    typescript: ~5.9.2
    '@biomejs/biome': 2.2.4
    husky: ^9.1.7
    turbo: ^2.5.6
    cross-env: ^10.0.0
    zod: ^4.1.12
    '@t3-oss/env-core': ^0.13.8

overrides:
  glob: ^11.0.1
  whatwg-url: ^14.0.0

nodeLinker: hoisted

preferWorkspacePackages: true

publicHoistPattern:
  - '*'

sharedWorkspaceLockfile: true

strictPeerDependencies: false