packages:
  - apps/**
  - packages/**

catalogs:
  base:
    '@biomejs/biome': 2.3.2
    '@t3-oss/env-core': ^0.13.8
    better-auth: 1.3.27
    husky: ^9.1.7
    turbo: ^2.6.3
    typescript: ~5.9.3
    zod: ^4.1.12

nodeLinker: hoisted

onlyBuiltDependencies:
  - bcrypt
  - esbuild

overrides:
  glob: ^11.0.1
  whatwg-url: ^14.0.0

preferWorkspacePackages: true

publicHoistPattern:
  - '*'

sharedWorkspaceLockfile: true

strictPeerDependencies: false
